
osx:
	java -jar JsTestDriver-1.3.2.jar --port 9876 --browser /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --tests all

linux:
	java -jar JsTestDriver-1.3.2.jar --port 9876 --browser `which chromium-browser`,`which firefox` --tests all
